---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first }}/cert.pem
  register: letsencrypt_cert

- name: Create webroot directory if it doesn't exist yet
  file:
    path: "{{ cert_item.webroot | default(certbot_webroot) }}"
    state: directory

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists

- name: Register certificate domains (if certbot_expand)
  shell: "{{ certbot_script }} certificates --cert-name {{ cert_item.domains | first | replace('*.', '') }} | grep Domains | cut -d':' -f2"
  changed_when: false
  register: letsencrypt_cert_domains_dirty
  when: certbot_expand and letsencrypt_cert.stat.exists

- name: Cleanup domain list (if certbot_expand)
  set_fact:
    letsencrypt_cert_domains: "{{ letsencrypt_cert_domains_dirty.stdout | trim | split(' ') | map('trim') | select('!=', '') | list | sort }}"
  when: certbot_expand and letsencrypt_cert.stat.exists

- name: Expand certbot certificate (if certbot_expand)
  command: "{{ certbot_create_command }}"
  when: certbot_expand and letsencrypt_cert.stat.exists and letsencrypt_cert_domains != cert_item.domains | map('trim') | select('!=', '') | list | sort
